language: minimal
sudo: required

env:
  - MESASDK_URL=http://www.astro.wisc.edu/~townsend/resource/download/mesasdk/
  - MESASDK_VERSION=20.3.2
  - MESASDK_TARFILE=mesasdk-x86_64-$MESASDK_VERSION.tar.gz
  - MESASDK_ROOT=$HOME/mesasdk

cache:
  directories:
    - $MESASDK_ROOT

install:
  - if test ! -e $MESASDK_TARFILE; then wget --user-agent="" $MESASDK_URL/$MESASDK_TARFILE; fi
  - if test ! -d $MESASDK_ROOT; then tar xvfz $MESASDK_TARFILE -C $HOME; fi
  - . ${MESASDK_ROOT}/bin/mesasdk_init.sh

script: make && make test
